plugins{
    id 'maven-publish'
    id 'signing'
}

java {
    withJavadocJar()
    withSourcesJar()
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = project.name
            from components.java
            versionMapping {
                usage('java-api') {
                    fromResolutionOf('runtimeClasspath')
                }
                usage('java-runtime') {
                    fromResolutionResult()
                }
            }
            pom {
                name = project.name
                description = 'The java version of the NVA datamodel'
                url = 'https://github.com/BIBSYSDEV/nva-language-java'
                licenses {
                    license {
                        name = 'MIT License'
                        url = 'https://www.opensource.org/licenses/mit-license.php'
                    }
                }
                developers {
                    developer {
                        name.set("NVA Team")
                        email.set("kontakt@sikt.no")
                        organization.set("Sikt")
                        organizationUrl.set("https://sikt.no/")
                    }
                }
                scm {
                    connection = 'scm:git:git://github.com/BIBSYSDEV/nva-language-java.git'
                    developerConnection = 'scm:git:ssh://github.com/BIBSYSDEV/nva-language-java.git'
                    url = 'https://github.com/BIBSYSDEV/nva-language-java/tree/main'
                }
            }
        }
    }
}

signing {
    required = { project.hasProperty("signingKey") }
    useInMemoryPgpKeys(findProperty('signingKey'),
            findProperty('signingPassword'))
    sign publishing.publications
}
