[versions]
errorprone = { strictly = '2.37.0' }
errorpronePlugin = { strictly = '4.1.0' }
junit = { strictly = '5.12.1' }
junit-platform = { strictly = '1.12.1'}
nexus = { strictly = '2.0.0' }
spotless = { strictly = '7.0.3' }

[libraries]
errorprone = { group = 'com.google.errorprone', name = 'error_prone_core', version.ref = 'errorprone' }
errorprone-plugin = { group = 'net.ltgt.errorprone', name = 'net.ltgt.errorprone.gradle.plugin', version.ref = 'errorpronePlugin' }
junit-jupiter = { group = 'org.junit.jupiter', name = 'junit-jupiter', version.ref = 'junit' }
junit-jupiter-params = { group = 'org.junit.jupiter', name = 'junit-jupiter-params', version.ref = 'junit' }
junit-jupiter-platform = { group = 'org.junit.platform', name = 'junit-platform-launcher', version.ref = 'junit-platform' }
nexus = { group = 'io.github.gradle-nexus', name = 'publish-plugin', version.ref = 'nexus' }
spotless = { group = 'com.diffplug.spotless', name = 'spotless-plugin-gradle', version.ref = 'spotless' }

[bundles]

testing = ['junit-jupiter', 'junit-jupiter-params', 'junit-jupiter-platform']
buildtools = ['errorprone', 'errorprone-plugin', 'nexus', 'spotless']
